"""velden voor followers toevoegen

Revision ID: 229f3a6b3492
Revises: 63ab50393114
Create Date: 2019-02-04 15:00:44.040298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229f3a6b3492'
down_revision = '63ab50393114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('followed_by', sa.Integer(), nullable=True),
    sa.Column('follows', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follows'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
